### ISSUE TITLE
Choose an OS LIcense

### ISSUE THREAD

**Issue by jm-janzen** [jm-janzen/termq-engine#49]
I'm not under any illusions that my first foray into ncurses will be legally troublesome; however, I would like to get into the habit of adding licenses earlier on to my projects.

Requirements:
- [x] Automatically linked in repo header as a [shortened license name](https://github.com/blog/2252-license-now-displayed-on-repository-overview) for ease.
- [x] Allows free use with attribution.
- [x] Provide a brief explanation of what this license means in the PR.

**Comment by crhallberg** [comment]
Do you want to restrict use at all?
- Share-alike?
- Commercial uses?

**Comment by jm-janzen** [comment]
I accepted a PR from someone for an MIT license just a few minutes ago, but you raise some good questions.

Does the MIT license allow commercial use as long as attribution is given?  I'm not sure that sits 100% well with me.  Is there a license that fits the requirements in the issue, which also disallows commercial use?  I'd accept a PR that does this.

**Comment by crhallberg** [comment]
[CC-BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/2.0/)

Creative Commons 
BY - Attribute
NC - Non-commercial
SA - Must use the same license

**Comment by crhallberg** [comment]
Also, sorry the double fix, I checked for open PRs, not closed ones.

**Comment by jm-janzen** [comment]
Created a new issue https://github.com/jm-janzen/termq/issues/55 for your PR to reference.  Thanks for for you work/knowledge.  Creative Commons sounds perfect.

**Comment by Calinou** [comment]
Please use CC BY or CC BY-SA instead of CC BY-NC-SA, as the non-commercial clause makes it not open source (incompatible with the OSI definition of open source).

Even better, use something like MIT, since it's more widely recognized.

**Comment by jm-janzen** [comment]
I see.  I'm [reading up](https://en.wikipedia.org/wiki/The_Open_Source_Definition#Definition) on this now.  I hadn't really considered it.  As a consumer, that's definitely how I prefer software.

**Comment by jm-janzen** [comment]
@Calinou after reading up on your suggestion, I agree with your opinion.  If you'd like to submit a PR including an MIT license, I'd gladly accept it.

**Comment by crhallberg** [comment]
I did not know that! Very interesting.

**Comment by jm-janzen** [comment]
Closed by https://github.com/jm-janzen/termq/pull/66.  I think we all learned a lot about OS licensing.  :)

**Comment by crhallberg** [comment]
I was doing more reading on this, and I honestly found the best summary to be [on Wikipedia](https://en.wikipedia.org/wiki/Creative_Commons#Criticism_of_the_non-commercial_license). I agree with this move. Thanks for the learning!

**Comment by jm-janzen** [comment]
Good reference.  I absolutely agree.  Intuitively, -NC makes a lot of sense, but when I think about all the OS libraries and packages I use, full free use is definitely how I'd prefer it as a consumer.
