### ISSUE TITLE
Add Creative Commons License

### ISSUE THREAD

**Issue by jm-janzen** [jm-janzen/termq-engine#55]
Based on discussion with @crhallberg

**Comment by crhallberg** [comment]
~~After doing more research, switching to a CC-BY-NC-SA license won't provide the shortcode in the top bar you desire. Will present a pull request anyway.~~

I was wrong! [Proof on my fork](https://github.com/crhallberg/termq).

**Comment by jm-janzen** [comment]
Merged!  Thank you for your research and work on this.  I'm glad I asked for help. :)
