### ISSUE TITLE
Add and Implement Makefile Generator

### ISSUE THREAD

**Issue by jm-janzen** [jm-janzen/termq-engine#64]
This ticket inspired by discussions [here](https://github.com/jm-janzen/termq/issues/50).

**Comment by bvbfan** [comment]
https://github.com/jm-janzen/termq/pull/65
Tested on Linux x64.

**Comment by bvbfan** [comment]
I made one _hack_
set(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR}/bin)

set(EXECUTABLE_OUTPUT_PATH ../../bin) will work if in parent dir
mkdir -p build && cd build
cmake ..
make -j4

**Comment by jm-janzen** [comment]
Looks good, but now the [travis-ci build is failing](https://travis-ci.org/jm-janzen/termq/jobs/166631094).  I'm away from home (at work) until later this week, so I can't test it locally.  Could you update the [travis yaml file](https://github.com/bvbfan/termq/blob/master/.travis.yml#L27)'s "script" to run `cmake` before running `make`?

I think this is the only issue.

**Comment by bvbfan** [comment]
Fixed.

**Comment by jm-janzen** [comment]
Closed by https://github.com/jm-janzen/termq/pull/65.  Thanks!
